services:
  - type: web
    name: laravel-on-render
    env: docker
    plan: free
    branch: master
    dockerfilePath: ./Dockerfile
    buildCommand: ""
    startCommand: ""
    autoDeploy: true
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        value: base64:VOTJ4ukkjZBLoiVOdvTSzaTuteilUAKuwUHBdQ22AAQ=

